[tool.black]
line-length = 120
target-version = ['py311']
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | .git
  | __pycache__
  | allure-results
  | allure-report
  | .pytest_cache
  | main.py
)/
'''

[tool.isort]
profile = "black"
line_length = 120
skip = [
    "venv",
    ".venv",
    "env",
    ".git",
    "__pycache__",
    "allure-results",
    "allure-report",
    ".pytest_cache",
]